# Generated by Django 5.0.6 on 2024-07-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_name_embalagem_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(max_length=100, verbose_name='Nome Fantasia do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_social',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome Social do Fornecedor'),
        ),
    ]
